@play @maintenance
Feature: Maintaining a documentation set

  Scenario Outline: A document due for attention is handled
    Given a <type> document that is <lifecycle>, whose dependencies are <deps>, held with <confidence> confidence
    When its owner's choice is applied
    Then it is handled by <expected>

    Examples:
      | type            | lifecycle | deps      | confidence | expected    |
      | tutorial        | FRESH     | changed   | high       | propose-fix |
      | tutorial        | FRESH     | changed   | medium     | propose-fix |
      | tutorial        | FRESH     | changed   | low        | propose-fix |
      | tutorial        | FRESH     | unchanged | high       | skip        |
      | tutorial        | FRESH     | unchanged | medium     | skip        |
      | tutorial        | FRESH     | unchanged | low        | review      |
      | tutorial        | FRESH     | none      | high       | skip        |
      | tutorial        | FRESH     | none      | medium     | skip        |
      | tutorial        | FRESH     | none      | low        | review      |
      | tutorial        | AGING     | changed   | high       | propose-fix |
      | tutorial        | AGING     | changed   | medium     | propose-fix |
      | tutorial        | AGING     | changed   | low        | propose-fix |
      | tutorial        | AGING     | unchanged | high       | bump        |
      | tutorial        | AGING     | unchanged | medium     | bump        |
      | tutorial        | AGING     | unchanged | low        | review      |
      | tutorial        | AGING     | none      | high       | bump        |
      | tutorial        | AGING     | none      | medium     | bump        |
      | tutorial        | AGING     | none      | low        | review      |
      | tutorial        | STALE     | changed   | high       | propose-fix |
      | tutorial        | STALE     | changed   | medium     | propose-fix |
      | tutorial        | STALE     | changed   | low        | propose-fix |
      | tutorial        | STALE     | unchanged | high       | review      |
      | tutorial        | STALE     | unchanged | medium     | review      |
      | tutorial        | STALE     | unchanged | low        | review      |
      | tutorial        | STALE     | none      | high       | review      |
      | tutorial        | STALE     | none      | medium     | review      |
      | tutorial        | STALE     | none      | low        | review      |
      | how-to          | FRESH     | changed   | high       | propose-fix |
      | how-to          | FRESH     | changed   | medium     | propose-fix |
      | how-to          | FRESH     | changed   | low        | propose-fix |
      | how-to          | FRESH     | unchanged | high       | skip        |
      | how-to          | FRESH     | unchanged | medium     | skip        |
      | how-to          | FRESH     | unchanged | low        | review      |
      | how-to          | FRESH     | none      | high       | skip        |
      | how-to          | FRESH     | none      | medium     | skip        |
      | how-to          | FRESH     | none      | low        | review      |
      | how-to          | AGING     | changed   | high       | propose-fix |
      | how-to          | AGING     | changed   | medium     | propose-fix |
      | how-to          | AGING     | changed   | low        | propose-fix |
      | how-to          | AGING     | unchanged | high       | bump        |
      | how-to          | AGING     | unchanged | medium     | bump        |
      | how-to          | AGING     | unchanged | low        | review      |
      | how-to          | AGING     | none      | high       | bump        |
      | how-to          | AGING     | none      | medium     | bump        |
      | how-to          | AGING     | none      | low        | review      |
      | how-to          | STALE     | changed   | high       | propose-fix |
      | how-to          | STALE     | changed   | medium     | propose-fix |
      | how-to          | STALE     | changed   | low        | propose-fix |
      | how-to          | STALE     | unchanged | high       | review      |
      | how-to          | STALE     | unchanged | medium     | review      |
      | how-to          | STALE     | unchanged | low        | review      |
      | how-to          | STALE     | none      | high       | review      |
      | how-to          | STALE     | none      | medium     | review      |
      | how-to          | STALE     | none      | low        | review      |
      | reference       | FRESH     | changed   | high       | propose-fix |
      | reference       | FRESH     | changed   | medium     | propose-fix |
      | reference       | FRESH     | changed   | low        | propose-fix |
      | reference       | FRESH     | unchanged | high       | skip        |
      | reference       | FRESH     | unchanged | medium     | skip        |
      | reference       | FRESH     | unchanged | low        | review      |
      | reference       | FRESH     | none      | high       | skip        |
      | reference       | FRESH     | none      | medium     | skip        |
      | reference       | FRESH     | none      | low        | review      |
      | reference       | AGING     | changed   | high       | propose-fix |
      | reference       | AGING     | changed   | medium     | propose-fix |
      | reference       | AGING     | changed   | low        | propose-fix |
      | reference       | AGING     | unchanged | high       | bump        |
      | reference       | AGING     | unchanged | medium     | bump        |
      | reference       | AGING     | unchanged | low        | review      |
      | reference       | AGING     | none      | high       | bump        |
      | reference       | AGING     | none      | medium     | bump        |
      | reference       | AGING     | none      | low        | review      |
      | reference       | STALE     | changed   | high       | propose-fix |
      | reference       | STALE     | changed   | medium     | propose-fix |
      | reference       | STALE     | changed   | low        | propose-fix |
      | reference       | STALE     | unchanged | high       | review      |
      | reference       | STALE     | unchanged | medium     | review      |
      | reference       | STALE     | unchanged | low        | review      |
      | reference       | STALE     | none      | high       | review      |
      | reference       | STALE     | none      | medium     | review      |
      | reference       | STALE     | none      | low        | review      |
      | explanation     | FRESH     | changed   | high       | propose-fix |
      | explanation     | FRESH     | changed   | medium     | propose-fix |
      | explanation     | FRESH     | changed   | low        | propose-fix |
      | explanation     | FRESH     | unchanged | high       | skip        |
      | explanation     | FRESH     | unchanged | medium     | skip        |
      | explanation     | FRESH     | unchanged | low        | review      |
      | explanation     | FRESH     | none      | high       | skip        |
      | explanation     | FRESH     | none      | medium     | skip        |
      | explanation     | FRESH     | none      | low        | review      |
      | explanation     | AGING     | changed   | high       | propose-fix |
      | explanation     | AGING     | changed   | medium     | propose-fix |
      | explanation     | AGING     | changed   | low        | propose-fix |
      | explanation     | AGING     | unchanged | high       | bump        |
      | explanation     | AGING     | unchanged | medium     | bump        |
      | explanation     | AGING     | unchanged | low        | review      |
      | explanation     | AGING     | none      | high       | bump        |
      | explanation     | AGING     | none      | medium     | bump        |
      | explanation     | AGING     | none      | low        | review      |
      | explanation     | STALE     | changed   | high       | propose-fix |
      | explanation     | STALE     | changed   | medium     | propose-fix |
      | explanation     | STALE     | changed   | low        | propose-fix |
      | explanation     | STALE     | unchanged | high       | review      |
      | explanation     | STALE     | unchanged | medium     | review      |
      | explanation     | STALE     | unchanged | low        | review      |
      | explanation     | STALE     | none      | high       | review      |
      | explanation     | STALE     | none      | medium     | review      |
      | explanation     | STALE     | none      | low        | review      |
      | decision-record | FRESH     | changed   | high       | propose-fix |
      | decision-record | FRESH     | changed   | medium     | propose-fix |
      | decision-record | FRESH     | changed   | low        | propose-fix |
      | decision-record | FRESH     | unchanged | high       | skip        |
      | decision-record | FRESH     | unchanged | medium     | skip        |
      | decision-record | FRESH     | unchanged | low        | review      |
      | decision-record | FRESH     | none      | high       | skip        |
      | decision-record | FRESH     | none      | medium     | skip        |
      | decision-record | FRESH     | none      | low        | review      |
      | decision-record | AGING     | changed   | high       | propose-fix |
      | decision-record | AGING     | changed   | medium     | propose-fix |
      | decision-record | AGING     | changed   | low        | propose-fix |
      | decision-record | AGING     | unchanged | high       | bump        |
      | decision-record | AGING     | unchanged | medium     | bump        |
      | decision-record | AGING     | unchanged | low        | review      |
      | decision-record | AGING     | none      | high       | bump        |
      | decision-record | AGING     | none      | medium     | bump        |
      | decision-record | AGING     | none      | low        | review      |
      | decision-record | STALE     | changed   | high       | propose-fix |
      | decision-record | STALE     | changed   | medium     | propose-fix |
      | decision-record | STALE     | changed   | low        | propose-fix |
      | decision-record | STALE     | unchanged | high       | review      |
      | decision-record | STALE     | unchanged | medium     | review      |
      | decision-record | STALE     | unchanged | low        | review      |
      | decision-record | STALE     | none      | high       | review      |
      | decision-record | STALE     | none      | medium     | review      |
      | decision-record | STALE     | none      | low        | review      |
