#!/usr/bin/env bun
/**
 * Split the consolidated user-story source into one .feature file per flow,
 * and regenerate the features index.
 *
 * Usage:
 *   bun scripts/user-stories/split-flows.ts <source.feature.md> <out-dir>
 *
 * The source holds a single ```gherkin block whose features are separated by
 * `# ═══` rules. Generated files are mirrors — edit the source, never the mirror.
 */

import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'fs'
import { basename, join } from 'path'

const [sourcePath, outDir] = process.argv.slice(2)

if (!sourcePath || !outDir) {
  console.error('Usage: bun scripts/user-stories/split-flows.ts <source.feature.md> <out-dir>')
  process.exit(1)
}

const source = readFileSync(sourcePath, 'utf-8')

const blockMatch = source.match(/```gherkin\n([\s\S]*?)\n```/)
if (!blockMatch) {
  console.error(`No gherkin block found in ${sourcePath}`)
  process.exit(1)
}

const block = blockMatch[1]!

const chunks = block
  .split(/^#\s*═+\s*$/m)
  .map((c) => c.replace(/^\n+/, '').replace(/\s+$/, ''))
  .filter(Boolean)

interface Flow {
  id: number
  title: string
  slug: string
  file: string
  scenarios: number
  tags: string[]
  story: string
}

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

const flows: Flow[] = []

mkdirSync(outDir, { recursive: true })

for (const chunk of chunks) {
  const featureMatch = chunk.match(/^Feature:\s*FLOW-(\d+)\s+(.+)$/m)
  if (!featureMatch) {
    console.error('Chunk has no `Feature: FLOW-NN <title>` line:\n' + chunk.slice(0, 120))
    process.exit(1)
  }

  const id = parseInt(featureMatch[1]!, 10)
  const title = featureMatch[2]!.trim()
  const slug = slugify(title)
  const file = `flow-${String(id).padStart(2, '0')}-${slug}.feature`

  const tags = (chunk.match(/^@[^\n]*$/m)?.[0] ?? '')
    .split(/\s+/)
    .filter((t) => t.startsWith('@'))

  const scenarios = (chunk.match(/^\s*Scenario(?: Outline)?:/gm) ?? []).length

  const storyBlock = chunk.match(/"""\n([\s\S]*?)\n\s*"""/)?.[1] ?? ''
  const story = storyBlock
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .join(' ')

  flows.push({ id, title, slug, file, scenarios, tags, story })
  writeFileSync(join(outDir, file), chunk + '\n')
}

flows.sort((a, b) => a.id - b.id)

// Drop stale mirrors left by earlier runs
const expected = new Set([...flows.map((f) => f.file), 'README.md'])
for (const entry of readdirSync(outDir)) {
  if (!expected.has(entry)) {
    rmSync(join(outDir, entry))
    console.log(`Removed stale mirror: ${entry}`)
  }
}

const totalScenarios = flows.reduce((sum, f) => sum + f.scenarios, 0)
const sourceName = basename(sourcePath)

const readme = [
  '<!-- generated by scripts/user-stories/split-flows.ts — do not edit -->',
  '',
  '# DEP User Stories — Index',
  '',
  `Source of truth: [\`../${sourceName}\`](../${sourceName}).`,
  'These files are generated mirrors — edit the source and re-run the splitter.',
  '',
  `${flows.length} flows, ${totalScenarios} scenarios.`,
  '',
  '| Flow | Story | Scenarios | Tags |',
  '| --- | --- | --- | --- |',
  ...flows.map(
    (f) =>
      `| [FLOW-${String(f.id).padStart(2, '0')} ${f.title}](${f.file}) | ${f.story} | ${f.scenarios} | ${f.tags.join(' ')} |`
  ),
  '',
].join('\n')

writeFileSync(join(outDir, 'README.md'), readme)

for (const f of flows) {
  console.log(`FLOW-${String(f.id).padStart(2, '0')} → ${f.file} (${f.scenarios} scenarios)`)
}
console.log(`\n${flows.length} flows, ${totalScenarios} scenarios → ${outDir}`)
